apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: main
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP