apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../overlays/podAndService/java-http

commonLabels:
  app.kubernetes.io/name: second-app
  app.kubernetes.io/part-of: uber-project

namePrefix: second-