apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../overlays/java-web

patchesJson6902:
- target:
    group: .*
    version: .*
    kind: .*
    name: .*
  path: patches/json6902/patch-metadata-name.yaml

commonLabels:
  app.kubernetes.io/name: second-app
  app.kubernetes.io/part-of: uber-project