apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../java

components:
- ../../../components/ports/https/deploymentAndService

commonLabels:
  app.kubernetes.io/component: web