apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../overlays/deploymentAndService/java-https

commonLabels:
  app.kubernetes.io/name: third-app
  app.kubernetes.io/part-of: uber-project

namePrefix: third-