apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME_PLACEHOLDER
spec:
  selector:
    name: DEPLOYMENT_NAME_PLACEHOLDER
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: CONTAINER_PORT_PLACEHOLDER