apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../bases/deploymentAndService

components:
- ../../../components/images/java

commonLabels:
  app.kubernetes.io/runtime: java