apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME_PLACEHOLDER
spec:
  replicas: 3
  selector:
    matchLabels:
      app: POD_NAME_PLACEHOLDER
  template:
    metadata:
      label:
        app: POD_NAME_PLACEHOLDER
    spec:
      containers:
      - name: POD_NAME_PLACEHOLDER